@WebApplication1_HostAddress = https://localhost:44308

GET {{WebApplication1_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApplication1_HostAddress}}/fruitbasket/1/orders/AGSY001
Accept: application/json

###