name: Build

on:
  push:
    branches: [ "Create-Nuget-package" ]
  pull_request:
    branches: [ "Create-Nuget-package" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: .NET Restore + Build + Pack + Push
        working-directory: ./src/RefactorHelper.App
        run: |
          dotnet restore "RefactorHelper.csproj"
          dotnet build "RefactorHelper.csproj" -o "${{ github.workspace }}/_output"  --no-restore\
          dotnet pack "RefactorHelper.csproj" -o "${{ github.workspace }}/_output/package"
          dotnet nuget push RefactorHelper.**.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json