name: pr-check

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: .NET Restore
        working-directory: ./src/ApiDiffChecker.App
        run: |
          dotnet restore "ApiDiffChecker.csproj"

      - name: .NET Build
        working-directory: ./src/ApiDiffChecker.App
        run: |
          dotnet build "ApiDiffChecker.csproj" -o "${{ github.workspace }}/_output"  --no-restore\

      - name: .NET Test
        working-directory: ./src/ApiDiffChecker.App
        run: |
          dotnet test "ApiDiffChecker.csproj" -o "${{ github.workspace }}/_output/test"
